#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2025.1.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Dec 01 16:18:20 CET 2025
# SW Build 6233196 on Thu Sep 11 21:27:11 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_SP_BRAM_RDO_behav -key {Behavioral:sim_1:Functional:tb_SP_BRAM_RDO} -tclbatch tb_SP_BRAM_RDO.tcl -log simulate.log"
xsim tb_SP_BRAM_RDO_behav -key {Behavioral:sim_1:Functional:tb_SP_BRAM_RDO} -tclbatch tb_SP_BRAM_RDO.tcl -log simulate.log

