#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2025.1.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Nov 16 18:18:19 CET 2025
# SW Build 6233196 on Thu Sep 11 21:27:11 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim full_adder_tb_behav -key {Behavioral:sim_1:Functional:full_adder_tb} -tclbatch full_adder_tb.tcl -log simulate.log"
xsim full_adder_tb_behav -key {Behavioral:sim_1:Functional:full_adder_tb} -tclbatch full_adder_tb.tcl -log simulate.log

